# Generated by Django 3.2.7 on 2021-09-12 19:13

from django.db import migrations, models
import django.db.models.deletion
import management.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[management.utils.validate_cpf], verbose_name='cpf')),
                ('type', models.CharField(choices=[('aluno', 'Aluno'), ('funcionario', 'Funcionário')], max_length=30, verbose_name='tipo')),
                ('registration', models.CharField(max_length=50, verbose_name='matrícula')),
                ('gender', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_binario', 'Não binário')], max_length=30, verbose_name='genero')),
                ('year_of_entry', models.IntegerField(verbose_name='ano de ingresso')),
                ('title', models.CharField(choices=[('especializacao', 'Especialização'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=30, verbose_name='título')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('acronym', models.CharField(max_length=50, unique=True, verbose_name='sigla')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('acronym', models.CharField(max_length=30, unique=True, verbose_name='sigla')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='tipo')),
                ('shift', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=50, verbose_name='turno')),
                ('description', models.TextField(max_length=200, verbose_name='descrição')),
                ('vegeterian_option', models.TextField(max_length=200, verbose_name='opção vegeratiana')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='preço')),
                ('paid', models.BooleanField(default=False, verbose_name='pago')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.consumer')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.consumer')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.course')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.consumer')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.department')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.department'),
        ),
    ]
